In [14]:
import pandas as pd
views = pd.read_csv(
    '../data/feed-views.log', 
    sep='\t',
    skiprows=[2, 3],    
    skipfooter=2,                
    names=['datetime', 'user'],
    engine='python'
)

In [15]:
views['datetime'] = pd.to_datetime(views['datetime'])

views['year'] = views['datetime'].dt.year
views['month'] = views['datetime'].dt.month
views['day'] = views['datetime'].dt.day
views['hour'] = views['datetime'].dt.hour
views['minute'] = views['datetime'].dt.minute
views['second'] = views['datetime'].dt.second

views.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1072 entries, 0 to 1071
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  1072 non-null   datetime64[ns]
 1   user      1072 non-null   object
 2   year      1072 non-null   int32
 3   month     1072 non-null   int32
 4   day       1072 non-null   int32
 5   hour      1072 non-null   int32
 6   minute    1072 non-null   int32
 7   second    1072 non-null   int32
dtypes: datetime64[ns](1), int32(6), object(1)
memory usage: 42.0+ KB

In [16]:
labels = ['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']
bins = [0, 4, 7, 11, 17, 20, 24]
views['daytime'] = pd.cut(views['hour'], bins=bins, labels=labels, right=False)

In [17]:
views.count()

datetime    1072
user        1072
year        1072
month       1072
day         1072
hour        1072
minute      1072
second      1072
daytime     1072
dtype: int64

In [18]:
views.daytime.value_counts()

daytime
evening          508
afternoon        250
early evening    145
night            129
morning           35
early morning      5
Name: count, dtype: int64

In [19]:
views.sort_values(['hour', 'minute', 'second'])

,datetime,user,year,month,day,hour,minute,second,daytime
942,2020-05-15 00:00:13.222265,valentina,2020,5,15,0,0,13,night
943,2020-05-15 00:01:05.153738,valentina,2020,5,15,0,1,5,night
561,2020-05-12 00:01:27.764025,pavel,2020,5,12,0,1,27,night
562,2020-05-12 00:01:38.444917,pavel,2020,5,12,0,1,38,night
563,2020-05-12 00:01:55.395042,pavel,2020,5,12,0,1,55,night
...,...,...,...,...,...,...,...,...,...
124,2020-04-29 23:48:14.208828,artem,2020,4,29,23,48,14,evening
244,2020-05-09 23:53:55.599821,anatoliy,2020,5,9,23,53,55,evening
245,2020-05-09 23:54:54.260791,pavel,2020,5,9,23,54,54,evening
940,2020-05-14 23:58:56.754866,valentina,2020,5,14,23,58,56,evening
941,2020-05-14 23:59:38.758438,alexander,2020,5,14,23,59,38,evening

In [20]:
night_max_hour = views[views['daytime'] == 'night']['hour'].max()
print(night_max_hour)
morning_min_hour = views[views['daytime'] == 'morning']['hour'].min()
print(morning_min_hour)
visit_night_hour = views[views['hour'] == night_max_hour]['user'].unique()
print(visit_night_hour)
visit_morning_hour = views[views['hour'] == morning_min_hour]['user'].unique()
print(visit_morning_hour)

3
8
['konstantin']
['alexander']

In [21]:
views['hour'].mode(0)

0    22
Name: hour, dtype: int32

In [22]:
views['daytime'].mode()[0]

'evening'

In [23]:
early_morning_users = views[views['daytime'] == 'morning'].nsmallest(3, 'hour')[['hour', 'user']]
early_morning_users

     hour       user
961     8  alexander
962     8  alexander
86      9      artem

In [24]:
lately_morning_users = views[views['daytime'] == 'morning'].nlargest(3, 'hour')[['hour', 'user']]
lately_morning_users

    hour        user
10    10  konstantin
11    10       maxim
12    10  konstantin

In [25]:
views.describe()

,datetime,year,month,day,hour,minute,second
count,1072,1072.0,1072.000000,1072.000000,1072.000000,1072.000000,1072.000000
mean,2020-05-10 09:30:16.241518592,2020.0,4.872201,13.531716,16.256530,29.602612,29.508396
min,2020-04-17 12:01:08.463179,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000
25%,2020-05-10 01:13:53.448644096,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000
50%,2020-05-11 22:48:35.302552832,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000
75%,2020-05-14 14:30:41.062071296,2020.0,5.000000,14.000000,22.000000,46.000000,45.000000
max,2020-05-21 23:23:49.995349,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000
std,NaN,0.0,0.334021,4.901354,6.960369,17.710471,17.424398

In [26]:
hour_stat = views['hour'].describe()
q1 = hour_stat['25%']
q3 = hour_stat['75%']
iqr = q3-q1
print(iqr)

9.0